apps/scraper/views.py
from flask import Blueprint, redirect, url_for, render_template
from .pyastro import Pyastro


scraper = Blueprint('scraper', __name__, template_folder='templates/scraper')
ALLTIMEFRAMES = []
ALLSUNSIGNS = []
ASTRO_OBJ = None
ZODIAC = {}


@scraper.before_request
def load_template():
    global ALLTIMEFRAMES, ALLSUNSIGNS, ASTRO_OBJ, ZODIAC
    ASTRO_OBJ = Pyastro(_json_filepath='static/data/zodiac.json')
    ALLTIMEFRAMES = [freq.strip() for freq in ASTRO_OBJ.timeframes.split(',')]
    ALLSUNSIGNS = [zodiac.strip() for zodiac in ASTRO_OBJ.sunsigns.split(',')]
    ZODIAC = ASTRO_OBJ.zodiac_details


## This page will show the horoscope based on given sign & freq
@scraper.route("/horoscope/<_sign>/<_freq>")
def show_horoscope(_sign, _freq):
    try:
        ## Get the horoscope
        ASTRO_OBJ.sign = _sign
        ASTRO_OBJ.frequency = _freq
        horoscope_data = ASTRO_OBJ.horoscope
        
        zodiac_details = None
        for zdc in ZODIAC:
            if zdc['name'].lower() == _sign.lower():
                zodiac_details = zdc.copy()
                break

        return render_template("horoscope.html", data=horoscope_data, sign=_sign, freq=_freq, timeframe=ALLTIMEFRAMES, zodiac=zodiac_details)     
    except Exception as e:
        return render_template("400.html", err_msg=str(e))


## The home page
@scraper.route("/home")
def home():
    return render_template("index.html", zodiac=ZODIAC)

apps/scraper/templates/scraper/horoscope.html
{%extends 'base.html'%}

{%block content%}
<div class="jumbotron">
    <div class="row col-md-12">
        <h1 class="display-4 col-md-6">{{sign.capitalize()}}</h1>
        <a href="{{url_for('scraper.home')}}"class="col-md-6 zodiac_home_link">Home</a>
    </div>

    <div class="card zodiac_font">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                {% for freq_value in timeframe %}
                <li class="nav-item">
                    <a class="{{ 'nav-link active' if freq_value.lower() == freq else 'nav-link' }}" href="{{url_for('scraper.show_horoscope', _sign=sign.lower(), _freq=freq_value.lower())}}">{{freq_value.capitalize()}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-body">
            <p>{{data}}</p>
        </div>
    </div>

    <hr class="my-4">
</div>

<div class="row col-sm-12 col-md-10 col-lg-8 mb-3 about_box zodiac_font">      
    <h3>About {{sign.capitalize()}}</h3>         
    <div class="col-sm-7 col-md-7 col-lg-6" style="tab-size: 8">
        <ul>
            <li>Date:&emsp;&emsp;&emsp;&emsp;{{zodiac.date}}</li>
            <li>Symbol:&emsp;&emsp;&emsp;{{zodiac.symbol}}</li>
            <li>Element:&emsp;&emsp;&ensp;{{zodiac.element}}</li>
            <li>Ruling Planet:&ensp;{{zodiac.ruling_planet}}</li>
        </ul>
    </div>
    <div class="col-sm-5 col-md-3 col-lg-2">
        <img class="zodiac_sign_img" src="/static/images/zodiac_sign/{{sign}}_zodiac.png" alt="{{sign}}">
    </div>

    <h4>Traits</h4>
    <br>
    <p>{{zodiac.character.gist}}</p>
</div>

    
{%endblock%}

apps/scraper/templates/scraper/index.html
{%extends 'base.html'%}

{%block content%}
<div class="jumbotron text-center">
    <h1 class="display-4">What's Your Rashi?</h1>
    <br>
    <div class="row">            
        {% for zodiac_ele in zodiac %}
        
            <div class="col-6 col-sm-6 col-md-4 col-lg-2 mb-3">
                <a class="text-body zodiac_box_link" href="{{url_for('scraper.show_horoscope', _sign=zodiac_ele.name.lower(), _freq='today')}}" >
                    <div class="card zodiac_box" data-toggle="tooltip" data-placement="bottom" title="{{zodiac_ele.name.capitalize()}}">
                        <img class="zodiac_symbol_img" src="/static/images/zodiac_symbol/{{zodiac_ele.name.lower()}}.png"  style="height: 100px; width: 100px" title="{{zodiac_ele.name.capitalize()}}" alt="{{zodiac_ele.name.capitalize()}}">
                        <div class="card-body">
                            {{zodiac_ele.name.capitalize()}}
                            <br>
                            <small class="text-muted">{{zodiac_ele.date}}</small>
                        </div>
                    </div> 
                </a>     
            </div>
        
        {% endfor %}            
    </div>
</div>
{%endblock%}